apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ezxd7k0wd-python
  janus-idp.io/tekton: ezxd7k0wd-python
  backstage.io/kubernetes-id: ezxd7k0wd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ezxd7k0wd-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
